Fix the file_test.go usage of pathOffset
This should really be: PathOffset
which is the name of the function in file.go, otherwise:
b (master)$ go test
 _/home/morrowc/scripts/git/trident/ext/_gopath/src/trident.li/pitchfork/lib
./file_test.go:22: undefined: pathOffset